package de.digitaldealer.cardsplease.ui

object NavigationRoutes {

    const val MAIN_SCREEN = "MAIN_SCREEN"
    const val START_SCREEN = "START_SCREEN"
    const val CENTRAL_DEVICE_START_SCREEN = "CENTRAL_DEVICE_START_SCREEN"
    const val SATELLITE_DEVICE_START_SCREEN = "SATELLITE_DEVICE_START_SCREEN"
    const val PLAYER_NICK_NAME_SCREEN = "PLAYER_NICK_NAME_SCREEN"
    const val PLAYER_HAND_SCREEN = "PLAYER_HAND_SCREEN"
}
