complexity:
  TooManyFunctions:
    active: false

coroutines:
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

formatting:
  MaximumLineLength:
    active: false
  NoWildcardImports:
    active: false
  PackageName:
    active: false

style:
  MagicNumber:
    active: true
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/Color.kt"
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    active: false

naming:
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][_A-Za-z0-9]*)*'